name: Deploy API to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile.api'
      - 'cloudbuild-api.yaml'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (API)
        run: |
          gcloud builds submit --config=cloudbuild-api.yaml \
            --project=mk-ai-project-473000

