name: Deploy Admin to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/web/**'
      - 'frontend/**'
      - 'Dockerfile.admin'
      - 'cloudbuild-admin.yaml'
      - '.github/workflows/deploy-admin.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (Admin)
        run: |
          gcloud builds submit --config=cloudbuild-admin.yaml \
            --project=mk-ai-project-473000

